version: '3.7'
services:
  panther_bot:
    build:
      context: .
      dockerfile: panther_bot_dockerfile
    image: pantherlily:v3.0
    container_name: panther_bot
    volumes:
      - .:/opt/code
    networks:
      - panther_network

    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 5

  panther_db:
    image: postgres
    container_name: panther_db
    env_file:
      - packages/private/PantherLily_Keys/database_docker_compose.env
    volumes:
      - panther_volume:/var/lib/postgresql/data/  # Path is where the container stores sql data
    ports:
      - 5432:5432
    networks:
      - panther_network
    restart: always

  panther_daemon:
    build:
      context: .
      dockerfile: panther_daemon_dockerfile
    image: panther_daemon:v1.0
    container_name: panther_daemon
    volumes:
      - .:/opt/code
    networks:
      - panther_network
    depends_on:
      - panther_db

    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 5

volumes:
  panther_volume:
    external: true
    name: panther_volume

networks:
  panther_network:
    external: true
    name: panther_network


# docker exec -t panther_db pg_dump -c -U pg -d pantherdb > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
# cat dump_15-01-2021_01_30_01.sql | docker exec -i panther_db psql -U pg -d pantherd



