version: '3.7'
services:
  disco_bot:
    image: ubuntu
    container_name: panther_bot3
    build: .
    volumes:
      - .:/app
  db:
    image: postgres
    container_name: panther_db
    env_file:
      - packages/private/database.env
    volumes:
    - database-volume:/var/lib/postgresql/data/  # Path is where the container stores sql data

volumes:
  database-volume:

