version: '3.8'
services:
  disco_bot:
    build: .                                    # Specify to use to Dockerfile
    container_name: panther_bot3
    build: .
    volumes:
      - .:/app
  db:
    image: postgres
    container_name: panther_db
    env_file:
      - packages/private/database.env
    volumes:
    - database-volume:/var/lib/postgresql/data/  # Path is where the container stores sql data
    ports:
      - 5432:5432

volumes:
  database-volume:

