version: '3.7'
services:
  disco_bot:
    build: .
    image: pantherlily:v3.0
    container_name: panther_bot3
    volumes:
      - .:/code
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - panther_network

networks:
  panther_network:
    external: true
    name: panther_network



