version: '3.7'
services:
  panther_db:
    image: postgres
    container_name: panther_db
    env_file:
      - database.env
    volumes:
    - panther_volume:/var/lib/postgresql/data/  # Path is where the container stores sql data
    ports:
      - 5432:5432
    networks:
      - panther_network

  panther_daemon:
    build:
      context: ../
      dockerfile: panther_daemon_dockerfile
    image: panther_daemon
    container_name: panther_daemon
    networks:
      - panther_network


# docker volume create --name=panther_volume
volumes:
  panther_volume:
    external: true
    name: panther_volume

networks:
  panther_network:
    name: panther_network
    external: false
